# alworldgen.py
# Cepheus Light World Generator by Omer Golan-Joel
# v0.1 - March 7th, 2020
# This is open source code, feel free to use it for any purpose
# For any questions, contact me at golan2072@gmail.com

# Import modules
import stellagama
import worldgenlib

# Functions


# Main
def sector_generator(maxrow, maxcolumn):
    sector_name = stellagama.savefile("secx")
    file_name = sector_name
    output = open(file_name, "w")
    output.write(file_name+'\r\n')
    output.write("Generated by the Cepheus Light\r\n")
    for column in range(1, maxcolumn+1):
        for row in range(1, maxrow+1):
            if stellagama.dice(1, 6) >= 4:
                if row <= 9:
                    row_location = "0%i" % row
                elif row >= 10:
                    row_location = "%i" % row
                if column <= 9:
                    column_location = "0%i" % column
                elif column >= 10:
                    column_location = "%i" % column
                world_hex = column_location+row_location
                world = worldgenlib.World()
                world_string = world_hex + " " + world.get_uwp_string() + "\r"
                output.write(world_string)
            else:
                pass
    output.close()


# Testing Area
sector_generator(10, 8)