# alworldgen.py
# Cepheus Light World Generator by Omer Golan-Joel
# v0.5 - March 7th, 2020
# This is open source code, feel free to use it for any purpose
# For any questions, contact me at golan2072@gmail.com

# Import modules
import stellagama
import worldgenlib
import openpyxl
from openpyxl.styles import Font

# Functions
def sector_generator(maxrow, maxcolumn):
    sector_name = stellagama.savefile("secx")
    output = open(sector_name, "w")
    output.write(sector_name+'\r\n')
    output.write("Generated by the Cepheus Light\r\n")
    for column in range(1, maxcolumn+1):
        for row in range(1, maxrow+1):
            if stellagama.dice(1, 6) >= 4:
                if row <= 9:
                    row_location = "0%i" % row
                elif row >= 10:
                    row_location = "%i" % row
                if column <= 9:
                    column_location = "0%i" % column
                elif column >= 10:
                    column_location = "%i" % column
                world_hex = column_location+row_location
                world = worldgenlib.World()
                world_string = world_hex + " " + world.get_uwp_string() + "\r"
                output.write(world_string)
            else:
                pass
    output.close()


def sector_generator_excel(maxrow, maxcolumn):
    file_name = stellagama.savefile("xlsx")
    sector_name = file_name.strip('.xlsx')
    workbook = openpyxl.Workbook()
    sheet = workbook.active
    sheet.title = sector_name
    sheet['A1'] = sector_name
    sheet['A1'].font = Font(size=16, bold=True)
    sheet['A2'] = "Generated by the Cepheus Light World Generator"
    sheet['A3'].font = Font(bold=True)
    sheet['B3'].font = Font(bold=True)
    sheet['C3'].font = Font(bold=True)
    sheet['D3'].font = Font(bold=True)
    sheet['E3'].font = Font(bold=True)
    sheet['F3'].font = Font(bold=True)
    sheet['A3'] = "Hex"
    sheet['B3'] = "UWP"
    sheet['C3'] = "Zone"
    sheet['D3'] = "Bases"
    sheet['E3'] = "Gas Giant"
    sheet['F3'] = "Trade Codes"
    excel_row = 3
    for column in range(1, maxcolumn+1):
        for row in range(1, maxrow+1):
            if stellagama.dice(1, 6) >= 4:
                excel_row += 1
                if row <= 9:
                    row_location = "0%i" % row
                elif row >= 10:
                    row_location = "%i" % row
                if column <= 9:
                    column_location = "0%i" % column
                elif column >= 10:
                    column_location = "%i" % column
                world_hex = column_location+row_location
                world = worldgenlib.World()
                sheet.cell(row=excel_row, column=1).value = world_hex
                sheet.cell(row=excel_row, column=2).value = world.get_uwp_string()
                sheet.cell(row=excel_row, column=3).value = world.zone
                sheet.cell(row=excel_row, column=4).value = world.base
                sheet.cell(row=excel_row, column=5).value = world.gas_giants
                sheet.cell(row=excel_row, column=6).value = world.trade_string
            else:
                pass
    workbook.save(file_name)


# Testing Area
sector_generator_excel(10, 8)